=== felleslosninger/efm-peppol-meldingsformat/eGoverment/schema/manifest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema version="1.0" targetNamespace="http://begrep.difi.no/sdp/schema_v10"
	xmlns="http://begrep.difi.no/sdp/schema_v10"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="manifest" type="Manifest"/>

	<xsd:complexType name="Manifest">
		<xsd:annotation>
			<xsd:documentation>
				Inneholder metadata relatert til hver fil i en forsendelse.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="hoveddokument" type="Dokument" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="vedlegg" type="Dokument" minOccurs="0" maxOccurs="200"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Dokument">
		<xsd:sequence>
			<xsd:element name="tittel" minOccurs="0" maxOccurs="1" type="Tittel">
				<xsd:annotation>
					<xsd:documentation>
						Emnet på dokumentet som skal vises til bruker når innlogget riktig sikkerhetsnivå.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="href" use="required">
			<xsd:annotation>
				<xsd:documentation>
					Navn på filen i dokumentpakken.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="4" />
					<xsd:maxLength value="100" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="mime" use="required">
			<xsd:annotation>
				<xsd:documentation>
					For tillatte MIME-typer, se http://begrep.difi.no/ (TODO)
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:minLength value="1" />
					<xsd:maxLength value="100" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>





    

    <xsd:complexType name="Tittel">
		<xsd:simpleContent>
			<xsd:extension base="TittelString">
				<xsd:attribute name="lang" type="Spraakkode" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:simpleType name="TittelString">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="255"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Spraakkode">
		<xsd:annotation>
			<xsd:documentation>
				Språkkode ihht ISO-639-1 (2 bokstaver)
			</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="2"></xsd:minLength>
			<xsd:maxLength value="2"></xsd:maxLength>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== felleslosninger/efm-peppol-meldingsformat/eGoverment/examples/administration/message/Content/asic/manifest.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest
  xmlns="http://begrep.difi.no/sdp/schema_v10"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://begrep.difi.no/sdp/schema_v10 ../../../../../schema/manifest.xsd ">

  <hoveddokument href="message.json" mime="application/json">
    <tittel lang="no">Vedtak</tittel>
  </hoveddokument>

  <vedlegg href="info.html" mime="text/html">
    <tittel lang="no">informasjon</tittel>
  </vedlegg>

  <vedlegg href="journal.txt" mime="text/plain">
    <tittel lang="no">journal</tittel>
  </vedlegg>

  <vedlegg href="bilde.png" mime="image/png">
    <tittel lang="no">bilde</tittel>
  </vedlegg>

</manifest>
